### ISSUE TITLE
SI and FN timestamps with nanosecond precision?

### ISSUE THREAD

**Issue by ikhosravi** [Velocidex/go-ntfs#17]
Hi,
I'm looking for a way to add more precise timestamp for SI and FN fields.
If I'm right, the actual resolution of the SI and FN timestamps in NTFS is 100 nanoseconds counting from Jan 1, 1601.
Could we get such an output in MFT module output?
Thanks in advance

**Comment by scudette** [comment]
Good point - we need to slightly refactor the code here:
https://github.com/Velocidex/go-ntfs/blob/master/parser/helpers.go#L28

to pass the nano seconds to the `time.Unix()` function.

**Comment by scudette** [comment]
This is now done
