### ISSUE TITLE
Error reading content on last page if unaligned

### ISSUE THREAD

**Issue by cugu** [Velocidex/go-ntfs#20]
If the `pageSize` is not aligned with the content (e.g. content: "abcd", pagesize: 3) the data from the last page is not read by the PagedReader.
``` go
r, _ := NewPagedReader(bytes.NewReader([]byte("abcd")), 3, 100)
buf :=  make([]byte, 1)
c, err = r.ReadAt(buf, 3)

// returns: c=0, buf=[]byte{0x00}, err=io.EOF
// should be: c=1, buf=[]byte{0x64}, err=nil
```

**Comment by scudette** [comment]
Hmm good find. I think because we used 1024 for the paged reader size it just never came up - because ntfs typically uses 1024 byte pages or larger it has to be aligned anyway.

But I can see if we increase the page reader to 16kb this can be a problem.

**Comment by cugu** [comment]
And for large images it is unlikely that the data is located in that last section.

Here is a fixed implementation: https://github.com/forensicanalysis/pagedreader/blob/master/reader.go

**Comment by scudette** [comment]
Please take a look at the current version and the test.

**Comment by cugu** [comment]
Seems to be fixed, my tests pass ;-) Thanks!
