### ISSUE TITLE
Documentation ?

### ISSUE THREAD

**Issue by phocean** [Velocidex/go-ntfs#31]
Are you planing to write some documentation?

I would love to reuse the package, but apparently I will have to read all the code.

**Comment by scudette** [comment]
This project is mostly used within Velociraptor - probably that is the best reference for how to use it
https://github.com/Velocidex/velociraptor/blob/master/vql/parsers/ntfs.go
https://github.com/Velocidex/velociraptor/blob/master/vql/windows/filesystems/ntfs_windows.go
